/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const Center = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'managerContact' : IDL.Text,
  'capacity' : IDL.Nat,
  'location' : IDL.Text,
  'managerName' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'endDate' : Timestamp,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'centerId' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'capacity' : IDL.Nat,
  'enrolledCount' : IDL.Nat,
  'durationWeeks' : IDL.Nat,
  'startDate' : Timestamp,
});
export const UserId = IDL.Text;
export const Education = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Opt(Timestamp),
  'userId' : UserId,
  'institution' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'degree' : IDL.Text,
  'startDate' : Timestamp,
});
export const Experience = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Opt(Timestamp),
  'userId' : UserId,
  'description' : IDL.Opt(IDL.Text),
  'positionTitle' : IDL.Text,
  'companyName' : IDL.Text,
  'isCurrent' : IDL.Bool,
  'startDate' : Timestamp,
});
export const Job = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'applicationsCount' : IDL.Nat,
  'jobType' : IDL.Text,
  'createdAt' : Timestamp,
  'education' : IDL.Text,
  'description' : IDL.Text,
  'companyEmail' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'employerId' : UserId,
  'companyName' : IDL.Text,
  'category' : IDL.Text,
  'companyWebsite' : IDL.Opt(IDL.Text),
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const PlacementDrive = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'driveDate' : Timestamp,
  'companyName' : IDL.Text,
  'positions' : IDL.Nat,
  'location' : IDL.Text,
});
export const Application = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'appliedAt' : Timestamp,
  'applicantId' : UserId,
  'jobId' : IDL.Text,
  'resumeUrl' : IDL.Opt(IDL.Text),
});
export const Result_5 = IDL.Variant({ 'ok' : Application, 'err' : IDL.Text });
export const StudentProfile = IDL.Record({
  'dateOfBirth' : IDL.Opt(Timestamp),
  'userId' : UserId,
  'motherName' : IDL.Opt(IDL.Text),
  'centerId' : IDL.Opt(IDL.Text),
  'fatherName' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'placementStatus' : IDL.Text,
  'educationLevel' : IDL.Opt(IDL.Text),
  'qualification' : IDL.Opt(IDL.Text),
  'familyIncome' : IDL.Opt(IDL.Text),
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Enrollment = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'studentId' : UserId,
  'progressPercent' : IDL.Nat,
  'enrolledAt' : Timestamp,
  'courseId' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : Enrollment, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'CenterManager' : IDL.Null,
  'JobSeeker' : IDL.Null,
  'Employer' : IDL.Null,
  'Student' : IDL.Null,
  'Admin' : IDL.Null,
});
export const User = IDL.Record({
  'id' : UserId,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
  'lastLogin' : IDL.Opt(Timestamp),
  'lastName' : IDL.Text,
  'phoneVerified' : IDL.Bool,
  'firstName' : IDL.Text,
});
export const JobSeekerProfile = IDL.Record({
  'country' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'zipCode' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'resumeUrl' : IDL.Opt(IDL.Text),
});
export const PlacementRecord = IDL.Record({
  'id' : IDL.Text,
  'studentId' : UserId,
  'testResult' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'driveId' : IDL.Text,
  'offerDetails' : IDL.Opt(IDL.Text),
  'offerStatus' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notifType' : IDL.Text,
  'userId' : UserId,
  'link' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
export const Result_4 = IDL.Variant({ 'ok' : Center, 'err' : IDL.Text });
export const Result_3 = IDL.Variant({ 'ok' : Course, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({ 'ok' : Job, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addCenter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Center],
      [],
    ),
  'addCourse' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Timestamp,
        Timestamp,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [Course],
      [],
    ),
  'addEducation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        Timestamp,
        IDL.Opt(Timestamp),
      ],
      [Education],
      [],
    ),
  'addExperience' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        Timestamp,
        IDL.Opt(Timestamp),
        IDL.Bool,
      ],
      [Experience],
      [],
    ),
  'addJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [Job],
      [],
    ),
  'addPlacementDrive' : IDL.Func(
      [IDL.Text, IDL.Text, Timestamp, IDL.Nat, IDL.Text],
      [PlacementDrive],
      [],
    ),
  'applyForJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result_5],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, StudentProfile],
      [StudentProfile],
      [],
    ),
  'deleteCenter' : IDL.Func([IDL.Text], [Result_6], []),
  'deleteEducation' : IDL.Func([IDL.Text], [Result_6], []),
  'deleteExperience' : IDL.Func([IDL.Text], [Result_6], []),
  'deleteJob' : IDL.Func([IDL.Text], [Result_6], []),
  'deleteProfile' : IDL.Func([IDL.Text], [Result_6], []),
  'enrollInCourse' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
  'getAllStudents' : IDL.Func([], [IDL.Vec(User)], []),
  'getApplicationsForJob' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
  'getCenter' : IDL.Func([IDL.Text], [IDL.Opt(Center)], []),
  'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], []),
  'getCourseEnrollments' : IDL.Func([IDL.Text], [IDL.Vec(Enrollment)], []),
  'getEducations' : IDL.Func([IDL.Text], [IDL.Vec(Education)], []),
  'getExperiences' : IDL.Func([IDL.Text], [IDL.Vec(Experience)], []),
  'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], []),
  'getJobSeekerProfile' : IDL.Func([IDL.Text], [IDL.Opt(JobSeekerProfile)], []),
  'getJobsByEmployer' : IDL.Func([IDL.Text], [IDL.Vec(Job)], []),
  'getMyApplications' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
  'getMyEnrollments' : IDL.Func([IDL.Text], [IDL.Vec(Enrollment)], []),
  'getMyPlacementRecord' : IDL.Func([IDL.Text], [IDL.Vec(PlacementRecord)], []),
  'getNotifications' : IDL.Func([IDL.Text], [IDL.Vec(Notification)], []),
  'getNotificationsWithCount' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'notifications' : IDL.Vec(Notification),
          'unreadCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getOtpStatus' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'attemptsLeft' : IDL.Nat,
          'expired' : IDL.Bool,
          'valid' : IDL.Bool,
        }),
      ],
      [],
    ),
  'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(StudentProfile)], []),
  'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserById' : IDL.Func([IDL.Text], [Result], []),
  'listCenters' : IDL.Func([], [IDL.Vec(Center)], []),
  'listCourses' : IDL.Func([], [IDL.Vec(Course)], []),
  'listJobs' : IDL.Func([], [IDL.Vec(Job)], []),
  'listPlacementDrives' : IDL.Func([], [IDL.Vec(PlacementDrive)], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [Result_6], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, UserRole],
      [Result],
      [],
    ),
  'seedSampleData' : IDL.Func([], [IDL.Text], []),
  'sendNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Notification],
      [],
    ),
  'sendOtp' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'ok' : IDL.Bool,
          'error' : IDL.Opt(IDL.Text),
          'sessionId' : IDL.Nat,
        }),
      ],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
  'updateCenter' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [Result_4],
      [],
    ),
  'updateCourse' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        Timestamp,
        Timestamp,
        IDL.Nat,
      ],
      [Result_3],
      [],
    ),
  'updateEnrollmentProgress' : IDL.Func([IDL.Text, IDL.Nat], [Result_2], []),
  'updateJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Result_1],
      [],
    ),
  'updateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'upsertJobSeekerProfile' : IDL.Func(
      [IDL.Text, JobSeekerProfile],
      [JobSeekerProfile],
      [],
    ),
  'verifyOtp' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [
        IDL.Record({
          'ok' : IDL.Bool,
          'userId' : IDL.Opt(IDL.Nat),
          'error' : IDL.Opt(IDL.Text),
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const Center = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'managerContact' : IDL.Text,
    'capacity' : IDL.Nat,
    'location' : IDL.Text,
    'managerName' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'endDate' : Timestamp,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'centerId' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'capacity' : IDL.Nat,
    'enrolledCount' : IDL.Nat,
    'durationWeeks' : IDL.Nat,
    'startDate' : Timestamp,
  });
  const UserId = IDL.Text;
  const Education = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Opt(Timestamp),
    'userId' : UserId,
    'institution' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'degree' : IDL.Text,
    'startDate' : Timestamp,
  });
  const Experience = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Opt(Timestamp),
    'userId' : UserId,
    'description' : IDL.Opt(IDL.Text),
    'positionTitle' : IDL.Text,
    'companyName' : IDL.Text,
    'isCurrent' : IDL.Bool,
    'startDate' : Timestamp,
  });
  const Job = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'applicationsCount' : IDL.Nat,
    'jobType' : IDL.Text,
    'createdAt' : Timestamp,
    'education' : IDL.Text,
    'description' : IDL.Text,
    'companyEmail' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'employerId' : UserId,
    'companyName' : IDL.Text,
    'category' : IDL.Text,
    'companyWebsite' : IDL.Opt(IDL.Text),
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const PlacementDrive = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'driveDate' : Timestamp,
    'companyName' : IDL.Text,
    'positions' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Application = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'appliedAt' : Timestamp,
    'applicantId' : UserId,
    'jobId' : IDL.Text,
    'resumeUrl' : IDL.Opt(IDL.Text),
  });
  const Result_5 = IDL.Variant({ 'ok' : Application, 'err' : IDL.Text });
  const StudentProfile = IDL.Record({
    'dateOfBirth' : IDL.Opt(Timestamp),
    'userId' : UserId,
    'motherName' : IDL.Opt(IDL.Text),
    'centerId' : IDL.Opt(IDL.Text),
    'fatherName' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'placementStatus' : IDL.Text,
    'educationLevel' : IDL.Opt(IDL.Text),
    'qualification' : IDL.Opt(IDL.Text),
    'familyIncome' : IDL.Opt(IDL.Text),
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Enrollment = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'studentId' : UserId,
    'progressPercent' : IDL.Nat,
    'enrolledAt' : Timestamp,
    'courseId' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : Enrollment, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'CenterManager' : IDL.Null,
    'JobSeeker' : IDL.Null,
    'Employer' : IDL.Null,
    'Student' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : UserId,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
    'lastLogin' : IDL.Opt(Timestamp),
    'lastName' : IDL.Text,
    'phoneVerified' : IDL.Bool,
    'firstName' : IDL.Text,
  });
  const JobSeekerProfile = IDL.Record({
    'country' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'zipCode' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'resumeUrl' : IDL.Opt(IDL.Text),
  });
  const PlacementRecord = IDL.Record({
    'id' : IDL.Text,
    'studentId' : UserId,
    'testResult' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'driveId' : IDL.Text,
    'offerDetails' : IDL.Opt(IDL.Text),
    'offerStatus' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notifType' : IDL.Text,
    'userId' : UserId,
    'link' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  const Result_4 = IDL.Variant({ 'ok' : Center, 'err' : IDL.Text });
  const Result_3 = IDL.Variant({ 'ok' : Course, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : Job, 'err' : IDL.Text });
  
  return IDL.Service({
    'addCenter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Center],
        [],
      ),
    'addCourse' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Timestamp,
          Timestamp,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [Course],
        [],
      ),
    'addEducation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          Timestamp,
          IDL.Opt(Timestamp),
        ],
        [Education],
        [],
      ),
    'addExperience' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          Timestamp,
          IDL.Opt(Timestamp),
          IDL.Bool,
        ],
        [Experience],
        [],
      ),
    'addJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [Job],
        [],
      ),
    'addPlacementDrive' : IDL.Func(
        [IDL.Text, IDL.Text, Timestamp, IDL.Nat, IDL.Text],
        [PlacementDrive],
        [],
      ),
    'applyForJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_5],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, StudentProfile],
        [StudentProfile],
        [],
      ),
    'deleteCenter' : IDL.Func([IDL.Text], [Result_6], []),
    'deleteEducation' : IDL.Func([IDL.Text], [Result_6], []),
    'deleteExperience' : IDL.Func([IDL.Text], [Result_6], []),
    'deleteJob' : IDL.Func([IDL.Text], [Result_6], []),
    'deleteProfile' : IDL.Func([IDL.Text], [Result_6], []),
    'enrollInCourse' : IDL.Func([IDL.Text, IDL.Text], [Result_2], []),
    'getAllStudents' : IDL.Func([], [IDL.Vec(User)], []),
    'getApplicationsForJob' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
    'getCenter' : IDL.Func([IDL.Text], [IDL.Opt(Center)], []),
    'getCourse' : IDL.Func([IDL.Text], [IDL.Opt(Course)], []),
    'getCourseEnrollments' : IDL.Func([IDL.Text], [IDL.Vec(Enrollment)], []),
    'getEducations' : IDL.Func([IDL.Text], [IDL.Vec(Education)], []),
    'getExperiences' : IDL.Func([IDL.Text], [IDL.Vec(Experience)], []),
    'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], []),
    'getJobSeekerProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(JobSeekerProfile)],
        [],
      ),
    'getJobsByEmployer' : IDL.Func([IDL.Text], [IDL.Vec(Job)], []),
    'getMyApplications' : IDL.Func([IDL.Text], [IDL.Vec(Application)], []),
    'getMyEnrollments' : IDL.Func([IDL.Text], [IDL.Vec(Enrollment)], []),
    'getMyPlacementRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlacementRecord)],
        [],
      ),
    'getNotifications' : IDL.Func([IDL.Text], [IDL.Vec(Notification)], []),
    'getNotificationsWithCount' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'notifications' : IDL.Vec(Notification),
            'unreadCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getOtpStatus' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'attemptsLeft' : IDL.Nat,
            'expired' : IDL.Bool,
            'valid' : IDL.Bool,
          }),
        ],
        [],
      ),
    'getProfile' : IDL.Func([IDL.Text], [IDL.Opt(StudentProfile)], []),
    'getUnreadCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserById' : IDL.Func([IDL.Text], [Result], []),
    'listCenters' : IDL.Func([], [IDL.Vec(Center)], []),
    'listCourses' : IDL.Func([], [IDL.Vec(Course)], []),
    'listJobs' : IDL.Func([], [IDL.Vec(Job)], []),
    'listPlacementDrives' : IDL.Func([], [IDL.Vec(PlacementDrive)], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [Result_6], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, UserRole],
        [Result],
        [],
      ),
    'seedSampleData' : IDL.Func([], [IDL.Text], []),
    'sendNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Notification],
        [],
      ),
    'sendOtp' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'ok' : IDL.Bool,
            'error' : IDL.Opt(IDL.Text),
            'sessionId' : IDL.Nat,
          }),
        ],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
    'updateCenter' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [Result_4],
        [],
      ),
    'updateCourse' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          Timestamp,
          Timestamp,
          IDL.Nat,
        ],
        [Result_3],
        [],
      ),
    'updateEnrollmentProgress' : IDL.Func([IDL.Text, IDL.Nat], [Result_2], []),
    'updateJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'updateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'upsertJobSeekerProfile' : IDL.Func(
        [IDL.Text, JobSeekerProfile],
        [JobSeekerProfile],
        [],
      ),
    'verifyOtp' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [
          IDL.Record({
            'ok' : IDL.Bool,
            'userId' : IDL.Opt(IDL.Nat),
            'error' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };