/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : string,
  'status' : string,
  'appliedAt' : Timestamp,
  'applicantId' : UserId,
  'jobId' : string,
  'resumeUrl' : [] | [string],
}
export interface Center {
  'id' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'managerContact' : string,
  'capacity' : bigint,
  'location' : string,
  'managerName' : string,
}
export interface Course {
  'id' : string,
  'title' : string,
  'endDate' : Timestamp,
  'createdAt' : Timestamp,
  'description' : string,
  'centerId' : [] | [string],
  'category' : string,
  'capacity' : bigint,
  'enrolledCount' : bigint,
  'durationWeeks' : bigint,
  'startDate' : Timestamp,
}
export interface Education {
  'id' : string,
  'endDate' : [] | [Timestamp],
  'userId' : UserId,
  'institution' : string,
  'description' : [] | [string],
  'degree' : string,
  'startDate' : Timestamp,
}
export interface Enrollment {
  'id' : string,
  'status' : string,
  'studentId' : UserId,
  'progressPercent' : bigint,
  'enrolledAt' : Timestamp,
  'courseId' : string,
}
export interface Experience {
  'id' : string,
  'endDate' : [] | [Timestamp],
  'userId' : UserId,
  'description' : [] | [string],
  'positionTitle' : string,
  'companyName' : string,
  'isCurrent' : boolean,
  'startDate' : Timestamp,
}
export interface Job {
  'id' : string,
  'title' : string,
  'applicationsCount' : bigint,
  'jobType' : string,
  'createdAt' : Timestamp,
  'education' : string,
  'description' : string,
  'companyEmail' : string,
  'logoUrl' : [] | [string],
  'employerId' : UserId,
  'companyName' : string,
  'category' : string,
  'companyWebsite' : [] | [string],
  'requirements' : string,
  'location' : string,
}
export interface JobSeekerProfile {
  'country' : [] | [string],
  'city' : [] | [string],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'zipCode' : [] | [string],
  'state' : [] | [string],
  'address' : [] | [string],
  'resumeUrl' : [] | [string],
}
export interface Notification {
  'id' : string,
  'notifType' : string,
  'userId' : UserId,
  'link' : [] | [string],
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
}
export interface PlacementDrive {
  'id' : string,
  'status' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'driveDate' : Timestamp,
  'companyName' : string,
  'positions' : bigint,
  'location' : string,
}
export interface PlacementRecord {
  'id' : string,
  'studentId' : UserId,
  'testResult' : [] | [string],
  'createdAt' : Timestamp,
  'driveId' : string,
  'offerDetails' : [] | [string],
  'offerStatus' : string,
}
export type Result = { 'ok' : User } |
  { 'err' : string };
export type Result_1 = { 'ok' : Job } |
  { 'err' : string };
export type Result_2 = { 'ok' : Enrollment } |
  { 'err' : string };
export type Result_3 = { 'ok' : Course } |
  { 'err' : string };
export type Result_4 = { 'ok' : Center } |
  { 'err' : string };
export type Result_5 = { 'ok' : Application } |
  { 'err' : string };
export type Result_6 = { 'ok' : null } |
  { 'err' : string };
export interface StudentProfile {
  'dateOfBirth' : [] | [Timestamp],
  'userId' : UserId,
  'motherName' : [] | [string],
  'centerId' : [] | [string],
  'fatherName' : [] | [string],
  'address' : [] | [string],
  'placementStatus' : string,
  'educationLevel' : [] | [string],
  'qualification' : [] | [string],
  'familyIncome' : [] | [string],
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
  'passwordHash' : string,
  'phone' : string,
  'lastLogin' : [] | [Timestamp],
  'lastName' : string,
  'phoneVerified' : boolean,
  'firstName' : string,
}
export type UserId = string;
export type UserRole = { 'CenterManager' : null } |
  { 'JobSeeker' : null } |
  { 'Employer' : null } |
  { 'Student' : null } |
  { 'Admin' : null };
export interface _SERVICE {
  'addCenter' : ActorMethod<[string, string, bigint, string, string], Center>,
  'addCourse' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      Timestamp,
      Timestamp,
      bigint,
      [] | [string],
    ],
    Course
  >,
  'addEducation' : ActorMethod<
    [string, string, string, [] | [string], Timestamp, [] | [Timestamp]],
    Education
  >,
  'addExperience' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      Timestamp,
      [] | [Timestamp],
      boolean,
    ],
    Experience
  >,
  'addJob' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
    ],
    Job
  >,
  'addPlacementDrive' : ActorMethod<
    [string, string, Timestamp, bigint, string],
    PlacementDrive
  >,
  'applyForJob' : ActorMethod<[string, string, [] | [string]], Result_5>,
  'createOrUpdateProfile' : ActorMethod<
    [string, StudentProfile],
    StudentProfile
  >,
  'deleteCenter' : ActorMethod<[string], Result_6>,
  'deleteEducation' : ActorMethod<[string], Result_6>,
  'deleteExperience' : ActorMethod<[string], Result_6>,
  'deleteJob' : ActorMethod<[string], Result_6>,
  'deleteProfile' : ActorMethod<[string], Result_6>,
  'enrollInCourse' : ActorMethod<[string, string], Result_2>,
  'getAllStudents' : ActorMethod<[], Array<User>>,
  'getApplicationsForJob' : ActorMethod<[string], Array<Application>>,
  'getCenter' : ActorMethod<[string], [] | [Center]>,
  'getCourse' : ActorMethod<[string], [] | [Course]>,
  'getCourseEnrollments' : ActorMethod<[string], Array<Enrollment>>,
  'getEducations' : ActorMethod<[string], Array<Education>>,
  'getExperiences' : ActorMethod<[string], Array<Experience>>,
  'getJob' : ActorMethod<[string], [] | [Job]>,
  'getJobSeekerProfile' : ActorMethod<[string], [] | [JobSeekerProfile]>,
  'getJobsByEmployer' : ActorMethod<[string], Array<Job>>,
  'getMyApplications' : ActorMethod<[string], Array<Application>>,
  'getMyEnrollments' : ActorMethod<[string], Array<Enrollment>>,
  'getMyPlacementRecord' : ActorMethod<[string], Array<PlacementRecord>>,
  'getNotifications' : ActorMethod<[string], Array<Notification>>,
  'getNotificationsWithCount' : ActorMethod<
    [string],
    { 'notifications' : Array<Notification>, 'unreadCount' : bigint }
  >,
  'getOtpStatus' : ActorMethod<
    [bigint],
    { 'attemptsLeft' : bigint, 'expired' : boolean, 'valid' : boolean }
  >,
  'getProfile' : ActorMethod<[string], [] | [StudentProfile]>,
  'getUnreadCount' : ActorMethod<[string], bigint>,
  'getUserById' : ActorMethod<[string], Result>,
  'listCenters' : ActorMethod<[], Array<Center>>,
  'listCourses' : ActorMethod<[], Array<Course>>,
  'listJobs' : ActorMethod<[], Array<Job>>,
  'listPlacementDrives' : ActorMethod<[], Array<PlacementDrive>>,
  'login' : ActorMethod<[string, string], Result>,
  'markNotificationRead' : ActorMethod<[string], Result_6>,
  'register' : ActorMethod<[string, string, string, string, UserRole], Result>,
  'seedSampleData' : ActorMethod<[], string>,
  'sendNotification' : ActorMethod<
    [string, string, string, [] | [string]],
    Notification
  >,
  'sendOtp' : ActorMethod<
    [string],
    { 'ok' : boolean, 'error' : [] | [string], 'sessionId' : bigint }
  >,
  'updateApplicationStatus' : ActorMethod<[string, string], Result_5>,
  'updateCenter' : ActorMethod<
    [string, string, string, bigint, string, string],
    Result_4
  >,
  'updateCourse' : ActorMethod<
    [string, string, string, string, bigint, Timestamp, Timestamp, bigint],
    Result_3
  >,
  'updateEnrollmentProgress' : ActorMethod<[string, bigint], Result_2>,
  'updateJob' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    Result_1
  >,
  'updateUser' : ActorMethod<[string, string, string, [] | [string]], Result>,
  'upsertJobSeekerProfile' : ActorMethod<
    [string, JobSeekerProfile],
    JobSeekerProfile
  >,
  'verifyOtp' : ActorMethod<
    [bigint, string],
    { 'ok' : boolean, 'userId' : [] | [bigint], 'error' : [] | [string] }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];