/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: Enrollment;
} | {
    __kind__: "err";
    err: string;
};
export interface JobSeekerProfile {
    country?: string;
    city?: string;
    userId: UserId;
    createdAt: Timestamp;
    zipCode?: string;
    state?: string;
    address?: string;
    resumeUrl?: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface User {
    id: UserId;
    createdAt: Timestamp;
    role: UserRole;
    isActive: boolean;
    email: string;
    passwordHash: string;
    phone?: string;
    lastLogin?: Timestamp;
    lastName: string;
    firstName: string;
}
export interface Education {
    id: string;
    endDate?: Timestamp;
    userId: UserId;
    institution: string;
    description?: string;
    degree: string;
    startDate: Timestamp;
}
export interface Enrollment {
    id: string;
    status: string;
    studentId: UserId;
    progressPercent: bigint;
    enrolledAt: Timestamp;
    courseId: string;
}
export interface Application {
    id: string;
    status: string;
    appliedAt: Timestamp;
    applicantId: UserId;
    jobId: string;
    resumeUrl?: string;
}
export type Result_5 = {
    __kind__: "ok";
    ok: Application;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Job;
} | {
    __kind__: "err";
    err: string;
};
export interface Course {
    id: string;
    title: string;
    endDate: Timestamp;
    createdAt: Timestamp;
    description: string;
    centerId?: string;
    category: string;
    capacity: bigint;
    enrolledCount: bigint;
    durationWeeks: bigint;
    startDate: Timestamp;
}
export type Result_4 = {
    __kind__: "ok";
    ok: Center;
} | {
    __kind__: "err";
    err: string;
};
export type UserId = string;
export interface StudentProfile {
    dateOfBirth?: Timestamp;
    userId: UserId;
    motherName?: string;
    centerId?: string;
    fatherName?: string;
    address?: string;
    placementStatus: string;
    educationLevel?: string;
    qualification?: string;
    familyIncome?: string;
}
export type Result = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Course;
} | {
    __kind__: "err";
    err: string;
};
export interface PlacementDrive {
    id: string;
    status: string;
    createdAt: Timestamp;
    description: string;
    driveDate: Timestamp;
    companyName: string;
    positions: bigint;
    location: string;
}
export interface Notification {
    id: string;
    notifType: string;
    userId: UserId;
    link?: string;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
}
export interface Job {
    id: string;
    title: string;
    applicationsCount: bigint;
    jobType: string;
    createdAt: Timestamp;
    education: string;
    description: string;
    companyEmail: string;
    logoUrl?: string;
    employerId: UserId;
    companyName: string;
    category: string;
    companyWebsite?: string;
    requirements: string;
    location: string;
}
export interface Experience {
    id: string;
    endDate?: Timestamp;
    userId: UserId;
    description?: string;
    positionTitle: string;
    companyName: string;
    isCurrent: boolean;
    startDate: Timestamp;
}
export interface Center {
    id: string;
    name: string;
    createdAt: Timestamp;
    managerContact: string;
    capacity: bigint;
    location: string;
    managerName: string;
}
export interface PlacementRecord {
    id: string;
    studentId: UserId;
    testResult?: string;
    createdAt: Timestamp;
    driveId: string;
    offerDetails?: string;
    offerStatus: string;
}
export enum UserRole {
    CenterManager = "CenterManager",
    JobSeeker = "JobSeeker",
    Employer = "Employer",
    Student = "Student",
    Admin = "Admin"
}
export interface backendInterface {
    addCenter(name: string, location: string, capacity: bigint, managerName: string, managerContact: string): Promise<Center>;
    addCourse(title: string, description: string, category: string, durationWeeks: bigint, startDate: Timestamp, endDate: Timestamp, capacity: bigint, centerId: string | null): Promise<Course>;
    addEducation(userId: string, institution: string, degree: string, description: string | null, startDate: Timestamp, endDate: Timestamp | null): Promise<Education>;
    addExperience(userId: string, companyName: string, positionTitle: string, description: string | null, startDate: Timestamp, endDate: Timestamp | null, isCurrent: boolean): Promise<Experience>;
    addJob(employerId: string, title: string, description: string, requirements: string, education: string, location: string, jobType: string, category: string, companyName: string, companyEmail: string, companyWebsite: string | null): Promise<Job>;
    addPlacementDrive(companyName: string, location: string, driveDate: Timestamp, positions: bigint, description: string): Promise<PlacementDrive>;
    applyForJob(jobId: string, applicantId: string, resumeUrl: string | null): Promise<Result_5>;
    createOrUpdateProfile(userId: string, profile: StudentProfile): Promise<StudentProfile>;
    deleteCenter(id: string): Promise<Result_6>;
    deleteEducation(id: string): Promise<Result_6>;
    deleteExperience(id: string): Promise<Result_6>;
    deleteJob(id: string): Promise<Result_6>;
    deleteProfile(userId: string): Promise<Result_6>;
    enrollInCourse(studentId: string, courseId: string): Promise<Result_2>;
    getAllStudents(): Promise<Array<User>>;
    getApplicationsForJob(jobId: string): Promise<Array<Application>>;
    getCenter(id: string): Promise<Center | null>;
    getCourse(id: string): Promise<Course | null>;
    getCourseEnrollments(courseId: string): Promise<Array<Enrollment>>;
    getEducations(userId: string): Promise<Array<Education>>;
    getExperiences(userId: string): Promise<Array<Experience>>;
    getJob(id: string): Promise<Job | null>;
    getJobSeekerProfile(userId: string): Promise<JobSeekerProfile | null>;
    getJobsByEmployer(employerId: string): Promise<Array<Job>>;
    getMyApplications(applicantId: string): Promise<Array<Application>>;
    getMyEnrollments(studentId: string): Promise<Array<Enrollment>>;
    getMyPlacementRecord(studentId: string): Promise<Array<PlacementRecord>>;
    getNotifications(userId: string): Promise<Array<Notification>>;
    getProfile(userId: string): Promise<StudentProfile | null>;
    getUserById(id: string): Promise<Result>;
    listCenters(): Promise<Array<Center>>;
    listCourses(): Promise<Array<Course>>;
    listJobs(): Promise<Array<Job>>;
    listPlacementDrives(): Promise<Array<PlacementDrive>>;
    login(email: string, passwordHash: string): Promise<Result>;
    markNotificationRead(notifId: string): Promise<Result_6>;
    register(email: string, passwordHash: string, firstName: string, lastName: string, role: UserRole): Promise<Result>;
    seedSampleData(): Promise<string>;
    sendNotification(userId: string, notifType: string, message: string, link: string | null): Promise<Notification>;
    updateApplicationStatus(applicationId: string, status: string): Promise<Result_5>;
    updateCenter(id: string, name: string, location: string, capacity: bigint, managerName: string, managerContact: string): Promise<Result_4>;
    updateCourse(id: string, title: string, description: string, category: string, durationWeeks: bigint, startDate: Timestamp, endDate: Timestamp, capacity: bigint): Promise<Result_3>;
    updateEnrollmentProgress(enrollmentId: string, progress: bigint): Promise<Result_2>;
    updateJob(id: string, title: string, description: string, requirements: string, education: string, location: string, jobType: string, category: string): Promise<Result_1>;
    updateUser(id: string, firstName: string, lastName: string, phone: string | null): Promise<Result>;
    upsertJobSeekerProfile(userId: string, profile: JobSeekerProfile): Promise<JobSeekerProfile>;
}
import type { Application as _Application, Center as _Center, Course as _Course, Education as _Education, Enrollment as _Enrollment, Experience as _Experience, Job as _Job, JobSeekerProfile as _JobSeekerProfile, Notification as _Notification, PlacementRecord as _PlacementRecord, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, StudentProfile as _StudentProfile, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCenter(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<Center> {
        if (this.processError) {
            try {
                const result = await this.actor.addCenter(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCenter(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addCourse(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Timestamp, arg5: Timestamp, arg6: bigint, arg7: string | null): Promise<Course> {
        if (this.processError) {
            try {
                const result = await this.actor.addCourse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
                return from_candid_Course_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCourse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
            return from_candid_Course_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addEducation(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: Timestamp, arg5: Timestamp | null): Promise<Education> {
        if (this.processError) {
            try {
                const result = await this.actor.addEducation(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
                return from_candid_Education_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEducation(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
            return from_candid_Education_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async addExperience(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: Timestamp, arg5: Timestamp | null, arg6: boolean): Promise<Experience> {
        if (this.processError) {
            try {
                const result = await this.actor.addExperience(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), arg6);
                return from_candid_Experience_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExperience(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), arg6);
            return from_candid_Experience_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addJob(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string | null): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg10));
                return from_candid_Job_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg10));
            return from_candid_Job_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPlacementDrive(arg0: string, arg1: string, arg2: Timestamp, arg3: bigint, arg4: string): Promise<PlacementDrive> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlacementDrive(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlacementDrive(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async applyForJob(arg0: string, arg1: string, arg2: string | null): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForJob(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_5_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForJob(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_5_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrUpdateProfile(arg0: string, arg1: StudentProfile): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0, to_candid_StudentProfile_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_StudentProfile_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0, to_candid_StudentProfile_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_StudentProfile_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCenter(arg0: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCenter(arg0);
                return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCenter(arg0);
            return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteEducation(arg0: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEducation(arg0);
                return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEducation(arg0);
            return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteExperience(arg0: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExperience(arg0);
                return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExperience(arg0);
            return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteJob(arg0: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProfile(arg0: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfile(arg0);
                return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfile(arg0);
            return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async enrollInCourse(arg0: string, arg1: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.enrollInCourse(arg0, arg1);
                return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enrollInCourse(arg0, arg1);
            return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationsForJob(arg0: string): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsForJob(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsForJob(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCenter(arg0: string): Promise<Center | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCenter(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCenter(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourse(arg0: string): Promise<Course | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourse(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourse(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCourseEnrollments(arg0: string): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCourseEnrollments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCourseEnrollments(arg0);
            return result;
        }
    }
    async getEducations(arg0: string): Promise<Array<Education>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEducations(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEducations(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExperiences(arg0: string): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperiences(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperiences(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: string): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobSeekerProfile(arg0: string): Promise<JobSeekerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobSeekerProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobSeekerProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByEmployer(arg0: string): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByEmployer(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByEmployer(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApplications(arg0: string): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEnrollments(arg0: string): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEnrollments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEnrollments(arg0);
            return result;
        }
    }
    async getMyPlacementRecord(arg0: string): Promise<Array<PlacementRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPlacementRecord(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPlacementRecord(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: string): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: string): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCenters(): Promise<Array<Center>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCenters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCenters();
            return result;
        }
    }
    async listCourses(): Promise<Array<Course>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCourses();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCourses();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPlacementDrives(): Promise<Array<PlacementDrive>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlacementDrives();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlacementDrives();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return from_candid_Result_6_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: string, arg1: string, arg2: string, arg3: string, arg4: UserRole): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2, arg3, to_candid_UserRole_n50(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2, arg3, to_candid_UserRole_n50(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedSampleData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async sendNotification(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Notification_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Notification_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateApplicationStatus(arg0: string, arg1: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, arg1);
                return from_candid_Result_5_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, arg1);
            return from_candid_Result_5_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCenter(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCenter(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_4_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCenter(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_4_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCourse(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: Timestamp, arg6: Timestamp, arg7: bigint): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_Result_3_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCourse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_Result_3_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEnrollmentProgress(arg0: string, arg1: bigint): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEnrollmentProgress(arg0, arg1);
                return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEnrollmentProgress(arg0, arg1);
            return from_candid_Result_2_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateJob(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return from_candid_Result_1_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return from_candid_Result_1_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertJobSeekerProfile(arg0: string, arg1: JobSeekerProfile): Promise<JobSeekerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertJobSeekerProfile(arg0, to_candid_JobSeekerProfile_n58(this._uploadFile, this._downloadFile, arg1));
                return from_candid_JobSeekerProfile_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertJobSeekerProfile(arg0, to_candid_JobSeekerProfile_n58(this._uploadFile, this._downloadFile, arg1));
            return from_candid_JobSeekerProfile_n37(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Application_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Course_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Course): Course {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Education_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Education): Education {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Experience_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Experience): Experience {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_JobSeekerProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobSeekerProfile): JobSeekerProfile {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_PlacementRecord_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlacementRecord): PlacementRecord {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): StudentProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_User_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Center]): Center | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Course]): Course | null {
    return value.length === 0 ? null : from_candid_Course_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobSeekerProfile]): JobSeekerProfile | null {
    return value.length === 0 ? null : from_candid_JobSeekerProfile_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : from_candid_StudentProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: [] | [_Timestamp];
    userId: _UserId;
    description: [] | [string];
    positionTitle: string;
    companyName: string;
    isCurrent: boolean;
    startDate: _Timestamp;
}): {
    id: string;
    endDate?: Timestamp;
    userId: UserId;
    description?: string;
    positionTitle: string;
    companyName: string;
    isCurrent: boolean;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.endDate)),
        userId: value.userId,
        description: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.description)),
        positionTitle: value.positionTitle,
        companyName: value.companyName,
        isCurrent: value.isCurrent,
        startDate: value.startDate
    };
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    applicationsCount: bigint;
    jobType: string;
    createdAt: _Timestamp;
    education: string;
    description: string;
    companyEmail: string;
    logoUrl: [] | [string];
    employerId: _UserId;
    companyName: string;
    category: string;
    companyWebsite: [] | [string];
    requirements: string;
    location: string;
}): {
    id: string;
    title: string;
    applicationsCount: bigint;
    jobType: string;
    createdAt: Timestamp;
    education: string;
    description: string;
    companyEmail: string;
    logoUrl?: string;
    employerId: UserId;
    companyName: string;
    category: string;
    companyWebsite?: string;
    requirements: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        applicationsCount: value.applicationsCount,
        jobType: value.jobType,
        createdAt: value.createdAt,
        education: value.education,
        description: value.description,
        companyEmail: value.companyEmail,
        logoUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.logoUrl)),
        employerId: value.employerId,
        companyName: value.companyName,
        category: value.category,
        companyWebsite: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.companyWebsite)),
        requirements: value.requirements,
        location: value.location
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    appliedAt: _Timestamp;
    applicantId: _UserId;
    jobId: string;
    resumeUrl: [] | [string];
}): {
    id: string;
    status: string;
    appliedAt: Timestamp;
    applicantId: UserId;
    jobId: string;
    resumeUrl?: string;
} {
    return {
        id: value.id,
        status: value.status,
        appliedAt: value.appliedAt,
        applicantId: value.applicantId,
        jobId: value.jobId,
        resumeUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.resumeUrl))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: [] | [_Timestamp];
    userId: _UserId;
    motherName: [] | [string];
    centerId: [] | [string];
    fatherName: [] | [string];
    address: [] | [string];
    placementStatus: string;
    educationLevel: [] | [string];
    qualification: [] | [string];
    familyIncome: [] | [string];
}): {
    dateOfBirth?: Timestamp;
    userId: UserId;
    motherName?: string;
    centerId?: string;
    fatherName?: string;
    address?: string;
    placementStatus: string;
    educationLevel?: string;
    qualification?: string;
    familyIncome?: string;
} {
    return {
        dateOfBirth: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.dateOfBirth)),
        userId: value.userId,
        motherName: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.motherName)),
        centerId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.centerId)),
        fatherName: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.fatherName)),
        address: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.address)),
        placementStatus: value.placementStatus,
        educationLevel: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.educationLevel)),
        qualification: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.qualification)),
        familyIncome: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.familyIncome))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    createdAt: _Timestamp;
    role: _UserRole;
    isActive: boolean;
    email: string;
    passwordHash: string;
    phone: [] | [string];
    lastLogin: [] | [_Timestamp];
    lastName: string;
    firstName: string;
}): {
    id: UserId;
    createdAt: Timestamp;
    role: UserRole;
    isActive: boolean;
    email: string;
    passwordHash: string;
    phone?: string;
    lastLogin?: Timestamp;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n28(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email,
        passwordHash: value.passwordHash,
        phone: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.phone)),
        lastLogin: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.lastLogin)),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    endDate: _Timestamp;
    createdAt: _Timestamp;
    description: string;
    centerId: [] | [string];
    category: string;
    capacity: bigint;
    enrolledCount: bigint;
    durationWeeks: bigint;
    startDate: _Timestamp;
}): {
    id: string;
    title: string;
    endDate: Timestamp;
    createdAt: Timestamp;
    description: string;
    centerId?: string;
    category: string;
    capacity: bigint;
    enrolledCount: bigint;
    durationWeeks: bigint;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        endDate: value.endDate,
        createdAt: value.createdAt,
        description: value.description,
        centerId: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.centerId)),
        category: value.category,
        capacity: value.capacity,
        enrolledCount: value.enrolledCount,
        durationWeeks: value.durationWeeks,
        startDate: value.startDate
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: [] | [string];
    city: [] | [string];
    userId: _UserId;
    createdAt: _Timestamp;
    zipCode: [] | [string];
    state: [] | [string];
    address: [] | [string];
    resumeUrl: [] | [string];
}): {
    country?: string;
    city?: string;
    userId: UserId;
    createdAt: Timestamp;
    zipCode?: string;
    state?: string;
    address?: string;
    resumeUrl?: string;
} {
    return {
        country: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.country)),
        city: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.city)),
        userId: value.userId,
        createdAt: value.createdAt,
        zipCode: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.zipCode)),
        state: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.state)),
        address: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.address)),
        resumeUrl: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.resumeUrl))
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    studentId: _UserId;
    testResult: [] | [string];
    createdAt: _Timestamp;
    driveId: string;
    offerDetails: [] | [string];
    offerStatus: string;
}): {
    id: string;
    studentId: UserId;
    testResult?: string;
    createdAt: Timestamp;
    driveId: string;
    offerDetails?: string;
    offerStatus: string;
} {
    return {
        id: value.id,
        studentId: value.studentId,
        testResult: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.testResult)),
        createdAt: value.createdAt,
        driveId: value.driveId,
        offerDetails: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.offerDetails)),
        offerStatus: value.offerStatus
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notifType: string;
    userId: _UserId;
    link: [] | [string];
    createdAt: _Timestamp;
    isRead: boolean;
    message: string;
}): {
    id: string;
    notifType: string;
    userId: UserId;
    link?: string;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
} {
    return {
        id: value.id,
        notifType: value.notifType,
        userId: value.userId,
        link: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.link)),
        createdAt: value.createdAt,
        isRead: value.isRead,
        message: value.message
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: [] | [_Timestamp];
    userId: _UserId;
    institution: string;
    description: [] | [string];
    degree: string;
    startDate: _Timestamp;
}): {
    id: string;
    endDate?: Timestamp;
    userId: UserId;
    institution: string;
    description?: string;
    degree: string;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.endDate)),
        userId: value.userId,
        institution: value.institution,
        description: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.description)),
        degree: value.degree,
        startDate: value.startDate
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Application;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Application;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Application_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Enrollment;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Enrollment;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CenterManager: null;
} | {
    JobSeeker: null;
} | {
    Employer: null;
} | {
    Student: null;
} | {
    Admin: null;
}): UserRole {
    return "CenterManager" in value ? UserRole.CenterManager : "JobSeeker" in value ? UserRole.JobSeeker : "Employer" in value ? UserRole.Employer : "Student" in value ? UserRole.Student : "Admin" in value ? UserRole.Admin : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n26(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Center;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Center;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Course;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Course;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Course_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Job;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Job;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Job_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Education>): Array<Education> {
    return value.map((x)=>from_candid_Education_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Experience>): Array<Experience> {
    return value.map((x)=>from_candid_Experience_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlacementRecord>): Array<PlacementRecord> {
    return value.map((x)=>from_candid_PlacementRecord_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Course>): Array<Course> {
    return value.map((x)=>from_candid_Course_n2(_uploadFile, _downloadFile, x));
}
function to_candid_JobSeekerProfile_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobSeekerProfile): _JobSeekerProfile {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_StudentProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentProfile): _StudentProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth?: Timestamp;
    userId: UserId;
    motherName?: string;
    centerId?: string;
    fatherName?: string;
    address?: string;
    placementStatus: string;
    educationLevel?: string;
    qualification?: string;
    familyIncome?: string;
}): {
    dateOfBirth: [] | [_Timestamp];
    userId: _UserId;
    motherName: [] | [string];
    centerId: [] | [string];
    fatherName: [] | [string];
    address: [] | [string];
    placementStatus: string;
    educationLevel: [] | [string];
    qualification: [] | [string];
    familyIncome: [] | [string];
} {
    return {
        dateOfBirth: value.dateOfBirth ? candid_some(value.dateOfBirth) : candid_none(),
        userId: value.userId,
        motherName: value.motherName ? candid_some(value.motherName) : candid_none(),
        centerId: value.centerId ? candid_some(value.centerId) : candid_none(),
        fatherName: value.fatherName ? candid_some(value.fatherName) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        placementStatus: value.placementStatus,
        educationLevel: value.educationLevel ? candid_some(value.educationLevel) : candid_none(),
        qualification: value.qualification ? candid_some(value.qualification) : candid_none(),
        familyIncome: value.familyIncome ? candid_some(value.familyIncome) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country?: string;
    city?: string;
    userId: UserId;
    createdAt: Timestamp;
    zipCode?: string;
    state?: string;
    address?: string;
    resumeUrl?: string;
}): {
    country: [] | [string];
    city: [] | [string];
    userId: _UserId;
    createdAt: _Timestamp;
    zipCode: [] | [string];
    state: [] | [string];
    address: [] | [string];
    resumeUrl: [] | [string];
} {
    return {
        country: value.country ? candid_some(value.country) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        userId: value.userId,
        createdAt: value.createdAt,
        zipCode: value.zipCode ? candid_some(value.zipCode) : candid_none(),
        state: value.state ? candid_some(value.state) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        resumeUrl: value.resumeUrl ? candid_some(value.resumeUrl) : candid_none()
    };
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    CenterManager: null;
} | {
    JobSeeker: null;
} | {
    Employer: null;
} | {
    Student: null;
} | {
    Admin: null;
} {
    return value == UserRole.CenterManager ? {
        CenterManager: null
    } : value == UserRole.JobSeeker ? {
        JobSeeker: null
    } : value == UserRole.Employer ? {
        Employer: null
    } : value == UserRole.Student ? {
        Student: null
    } : value == UserRole.Admin ? {
        Admin: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
